// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/v1/storage.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_api_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Manifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockCids     []string               `protobuf:"bytes,1,rep,name=block_cids,json=blockCids,proto3" json:"block_cids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_api_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_api_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *Manifest) GetBlockCids() []string {
	if x != nil {
		return x.BlockCids
	}
	return nil
}

var File_api_v1_storage_proto protoreflect.FileDescriptor

const file_api_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/storage.proto\x12\n" +
	"storage.v1\"\x1b\n" +
	"\x05Block\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\")\n" +
	"\bManifest\x12\x1d\n" +
	"\n" +
	"block_cids\x18\x01 \x03(\tR\tblockCidsB'Z%github.com/Yashh56/p2p-storage/api/v1b\x06proto3"

var (
	file_api_v1_storage_proto_rawDescOnce sync.Once
	file_api_v1_storage_proto_rawDescData []byte
)

func file_api_v1_storage_proto_rawDescGZIP() []byte {
	file_api_v1_storage_proto_rawDescOnce.Do(func() {
		file_api_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_storage_proto_rawDesc), len(file_api_v1_storage_proto_rawDesc)))
	})
	return file_api_v1_storage_proto_rawDescData
}

var file_api_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_storage_proto_goTypes = []any{
	(*Block)(nil),    // 0: storage.v1.Block
	(*Manifest)(nil), // 1: storage.v1.Manifest
}
var file_api_v1_storage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_storage_proto_init() }
func file_api_v1_storage_proto_init() {
	if File_api_v1_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_storage_proto_rawDesc), len(file_api_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_storage_proto_goTypes,
		DependencyIndexes: file_api_v1_storage_proto_depIdxs,
		MessageInfos:      file_api_v1_storage_proto_msgTypes,
	}.Build()
	File_api_v1_storage_proto = out.File
	file_api_v1_storage_proto_goTypes = nil
	file_api_v1_storage_proto_depIdxs = nil
}
